### ISSUE TITLE
Incompatible With Glide Package Manager

### ISSUE THREAD

**Issue by armsnyder** [mediocregopher/radix#50]
I'm working on a project which uses Glide for Go package management.

In my `glide.yml` I have:
```yml
- package: github.com/mediocregopher/radix
  version: v3.0.0
```

When I run `glide update` I get an error:
```
[ERROR] Error scanning github.com/mediocregopher/radix/v3/resp: cannot find package "." in:
        /Users/asnyder/.glide/cache/src/https-github.com-mediocregopher-radix/v3/resp
[ERROR] Error scanning github.com/mediocregopher/radix/v3/resp/resp2: cannot find package "." in:
        /Users/asnyder/.glide/cache/src/https-github.com-mediocregopher-radix/v3/resp/resp2
```

For now I have worked around this by adding these additional lines to my `glide.yml`:
```yml
ignore:
- github.com/mediocregopher/radix/v3/resp
- github.com/mediocregopher/radix/v3/resp/resp2
```

However, by doing this, I am now unable to use any types from the `resp` package, which means I can't do any custom marshaling/unmarshaling. If I try using one of these types, I get Go compilation errors. For example, this is what I get when I try to mock a Conn type using gomock:
```
./cache_impl_test.go:56:12: cannot use a (type *mock_radix.MockConn) as type radix.Conn in argument to arg.Run:
	*mock_radix.MockConn does not implement radix.Conn (wrong type for Decode method)
		have Decode("github.com/lyft/ratelimit/vendor/github.com/mediocregopher/radix/resp".Unmarshaler) error
		want Decode("github.com/mediocregopher/radix/resp".Unmarshaler) error
```

So it looks like ignoring those resp packages in my glide.yml is not the correct approach. I'm not super familiar with Go's new module system, but I think that's related to the issue here. I was not able to find literature online about Glide + Go modules.

Is there a recommended way of using radix with Glide?

I have also tried these other variations of my glide.yml but to no avail.

```yml
- package: github.com/mediocregopher/radix/v3
  version: v3.0.0
```

```yml
- package: github.com/mediocregopher/radix
  version: v3.0.0
  subpackages:
  - v3
```

```yml
- package: github.com/mediocregopher/radix
  version: v3.0.0
  subpackages:
  - v3
  - resp
  - resp/resp2
```

```yml
- package: github.com/mediocregopher/radix
  version: v3.0.0
  subpackages:
  - v3
  - v3/resp
  - v3/resp/resp2
```
